version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data:Z
      
  web:
    build: .
    command: bash startup.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      
volumes:
    postgres-data:
        external: true